apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  labels:
    cni: calico
  name: joe-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureCluster
    name: joe-test
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureCluster
metadata:
  name: joe-test
  namespace: default
spec:
  location: eastus
  networkSpec:
    vnet:
      name: joe-test-vnet
  resourceGroup: joe-test
  subscriptionID: bbda620e-ad6d-4440-8ba0-ba1297702503
