---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureMachine
metadata:
  name: joe-test-control-plane-0
  namespace: default
spec:
  location: eastus
  osDisk:
    diskSizeGB: 128
    managedDisk:
      storageAccountType: Premium_LRS
    osType: Linux
  sshPublicKey: ""
  vmSize: Standard_D2s_v3
  image:
    marketplace:
      publisher: Canonical
      sku: 18.04-LTS
      offer: UbuntuServer
      version: latest
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KThreesConfig
metadata:
  name: joe-test-control-plane-0
  namespace: default
spec:
  # Add fields here
  foo: asdfasdsa
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: joe-test
    cluster.x-k8s.io/control-plane: ""
  name: joe-test-control-plane-0
  namespace: default
spec:
  version: v1.18.2
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: KThreesConfig
      name: joe-test-control-plane-0
  clusterName: joe-test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureMachine
    name: joe-test-control-plane-0
  