apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MaasMachineTemplate
metadata:
  name: edge-cp
  namespace: edge
spec:
  template:
    spec:
      minCPU: 2
      minMemory: 4096
      image: u-1804-0-k-11912-0